### ISSUE TITLE
no backend :)

### ISSUE THREAD

**Issue by akbarisroilov** [r48n34/db-erd-gen#3]
hello! 
i am Nick, full stack dev (mostly backend)
i am really interested in developing this project.
it would be nice to have ability to save and share diagrams or draw with friends.
i can integrate backend if you would like (I use Django btw)
contact me if you agree: nickphilomath@gmail.com

**Comment by r48n34** [comment]
Sorry for the late reply.

The original plan of this project is for a low-cost local base db scheme design tools, which will not run the same as other online existing cloud base tools. Hence, there will be no plan for implementing any server for data storage/keeping or other OATH features.

Yet, the current web supports an export and import scheme that may help you to share diagrams with others (In top nav -> File -> Export JSON / Import JSON).

Once again, thank you for the ideas.
